export interface Theme {
  name: string;
  key: string;
  headerBackground: string;
  headerForeground: string;
  backgroundPrimary: string;
  backgroundSecondary: string;
  profileBorder: string;
  textPrimary: string;
  textSecondary: string;
  icons: string;
  footerBackground: string;
  footerForeground: string;
}

type ThemeCollection = { [key: string]: Theme };

export default <ThemeCollection>{
  default: {
    name: "Digital Eyes",
    key: "default",
    headerBackground: "#0E0E0E",
    headerForeground: "#FFFFFF",
    backgroundPrimary: "#0E0E0E",
    backgroundSecondary: "#242424",
    profileBorder: "#0E0E0E",
    textPrimary: "#FFFFFF",
    textSecondary: "#9F9F9F",
    icons: "#FFFFFF",
    footerBackground: "#181818",
    footerForeground: "#FFFFFF",
  },
  solana: {
    name: "Solana",
    key: "solana",
    headerBackground: "#101921",
    headerForeground: "#FFFFFF",
    backgroundPrimary: "#101921",
    backgroundSecondary: "#1F2529",
    profileBorder: "#101921",
    textPrimary: "#FFFFFF",
    textSecondary: "#6A6C6D",
    icons: "#00FFA3",
    footerBackground: "#050E15",
    footerForeground: "#FFFFFF",
  },
  mint: {
    name: "Mint",
    key: "mint",
    headerBackground: "#004643",
    headerForeground: "#fffff1",
    backgroundPrimary: "#004643",
    backgroundSecondary: "#ABD1C6",
    profileBorder: "#004643",
    textPrimary: "#FFFFFF",
    textSecondary: "#ABD1C6",
    icons: "#ABD1C6",
    footerBackground: "#001E1D",
    footerForeground: "#FFFFF1",
  },
  coffee: {
    name: "Coffee",
    key: "coffee",
    headerBackground: "#55423D",
    headerForeground: "#fffff1",
    backgroundPrimary: "#55423D",
    backgroundSecondary: "#CC9A8B",
    profileBorder: "#55423D",
    textPrimary: "#FFFFFF",
    textSecondary: "#CC9A8B",
    icons: "#CC9A8B",
    footerBackground: "#443533",
    footerForeground: "#FFFFF1",
  },
  greenhouse: {
    name: "Greenhouse",
    key: "greenhouse",
    headerBackground: "#5cdb95",
    headerForeground: "#05386b",
    backgroundPrimary: "#5cdb95",
    backgroundSecondary: "#8ee4af",
    profileBorder: "#5cdb95",
    textPrimary: "#edf5e1",
    textSecondary: "#edf5e1",
    icons: "#05386b",
    footerBackground: "#379683",
    footerForeground: "#edf5e1",
  },
  polarize: {
    name: "Polarize",
    key: "polarize",
    headerBackground: "#3feee6",
    headerForeground: "#000000",
    backgroundPrimary: "#fc4445",
    backgroundSecondary: "#3feee6",
    profileBorder: "#fc4445",
    textPrimary: "#000000",
    textSecondary: "#1d1d1d",
    icons: "#000000",
    footerBackground: "#fc1460",
    footerForeground: "#000000",
  },
  deepsea: {
    name: "Deep Sea",
    key: "deepsea",
    headerBackground: "#0c0032",
    headerForeground: "#fff",
    backgroundPrimary: "#0c0032",
    backgroundSecondary: "#222",
    profileBorder: "#0c0032",
    textPrimary: "#3500d3",
    textSecondary: "#555",
    icons: "#3500d3",
    footerBackground: "#282828",
    footerForeground: "#fff",
  },
  bubblegum: {
    name: "Bubble gum",
    key: "bubblegum",
    headerBackground: "#f070a1",
    headerForeground: "#1d1111",
    backgroundPrimary: "#16ffbd",
    backgroundSecondary: "#439f76",
    profileBorder: "#16ffbd",
    textPrimary: "#f070a1",
    textSecondary: "#1d1d1d",
    icons: "#f070a1",
    footerBackground: "#12c998",
    footerForeground: "#fff",
  },
  dracula: {
    name: "Dracula",
    key: "dracula",
    headerBackground: "#282a36",
    headerForeground: "#f8f8f2",
    backgroundPrimary: "#282a36",
    backgroundSecondary: "#44475a",
    profileBorder: "#282a36",
    textPrimary: "#50fa7b",
    textSecondary: "#f8f8f2",
    icons: "#bd93f9",
    footerBackground: "#6272a4",
    footerForeground: "#50fa7b",
  },
  light: {
    name: "Flashbang",
    key: "light",
    headerBackground: "#F8F5F2",
    headerForeground: "#202020",
    backgroundPrimary: "#F8F5F2",
    backgroundSecondary: "#E5E3E0",
    profileBorder: "#F8F5F2",
    textPrimary: "#0A0A0A",
    textSecondary: "#636363",
    icons: "#21A9E6",
    footerBackground: "#E9E8E7",
    footerForeground: "#202020",
  },
};
